name: CI/CD - WEB-Jouskaio.me

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Upgrade checkout action
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      # Install OpenVPN
      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved

      # Create VPN Config File
      - name: Create VPN Config File
        run: echo "${{ secrets.VPN_CONFIG }}" > vpn_config.ovpn

      # Connect to VPN
      - name: Connect to VPN
        uses: "kota65535/github-openvpn-connect-action@v2"
        with:
          config_file: vpn_config.ovpn

      # Build and Deploy
      - name: Use SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/WEB-Jouskaio.me
            git pull origin main
            npm install --legacy-peer-deps
            npm run build
            pm2 restart nextjs
