name: CI/CD - WEB-Jouskaio.me
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Mise à jour de l'action checkout
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      # Installe les dépendances
      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      # Exécute les tests
      #- name: Run Tests
      #  run: npm run test

      # Construit l'application Next.js
      - name: Build
        run: npm run build

      # Installe OpenVPN
      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved

      # Crée le fichier de configuration du VPN en utilisant le contenu du secret
      - name: Create VPN Config File
        run: echo "${{ secrets.VPN_CONFIG }}" > vpn_config.ovpn

      # Connecte au VPN
      - name: Connect to VPN
        uses: "kota65535/github-openvpn-connect-action@v2"
        with:
          config: vpn_config.ovpn

      - name: Use SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/WEB-Jouskaio.me
            git pull origin main
            npm install --legacy-peer-deps
            npm run build
            pm2 restart nextjs
