name: CI/CD - WEB-Jouskaio.me

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Install OpenVPN and Check VPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved
          echo "${{ secrets.VPN_CONFIG }}" > vpn_config.ovpn
          openvpn --config vpn_config.ovpn --daemon
          sleep 10
          ifconfig | grep tun0 || { echo "VPN connection failed"; exit 1; }

      - name: Test SSH Connection
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/private_key
          chmod 600 /tmp/private_key
          ssh -vvv -o StrictHostKeyChecking=no -i /tmp/private_key ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} whoami

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_USERNAME }}
          TARGET: "/home/debian/Documents/jouskaio.me/WEB-Jouskaio.me"
          EXCLUDE: "/dist/, /node_modules/"
          SCRIPT_AFTER: |
            set -e
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            cd /home/debian/Documents/jouskaio.me/WEB-Jouskaio.me
            git fetch --all
            git reset --hard origin/main
            if [ ! -d "node_modules" ]; then yarn install; fi
            yarn build
            pm2 reload ecosystem.config.js --env production