name: CI/CD - WEB-Jouskaio.me

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Upgrade checkout action
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      # Install OpenVPN
      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved

      # Create VPN Config File
      - name: Create VPN Config File
        run: echo "${{ secrets.VPN_CONFIG }}" > vpn_config.ovpn

      # Connect to VPN
      - name: Connect to VPN
        uses: "kota65535/github-openvpn-connect-action@v2"
        with:
          config_file: vpn_config.ovpn

      # Build & Deploy
      - name: Deploy to remote server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_USERNAME }}
          TARGET: "/root/WEB-Jouskaio.me"
          EXCLUDE: "/dist/, /node_modules/"
          SCRIPT_BEFORE: |
            echo "Running SCRIPT_BEFORE"
            whoami
            pwd
          SCRIPT_AFTER: |
            echo "Running SCRIPT_AFTER"
            whoami
            git pull origin main
            yarn install
            next build
            pm2 restart all
