name: CI/CD - WEB-Jouskaio.me

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Upgrade checkout action
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      # Install OpenVPN
      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved

      # Create VPN Config File
      - name: Create VPN Config File
        run: echo "${{ secrets.VPN_CONFIG }}" > vpn_config.ovpn

      # Connect to VPN
      - name: Connect to VPN
        uses: "kota65535/github-openvpn-connect-action@v2"
        with:
          config_file: vpn_config.ovpn

      # Test SSH Connection
      - name: Test SSH Connection
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/private_key
          chmod 600 /tmp/private_key
          ssh -vvv -o StrictHostKeyChecking=no -i /tmp/private_key ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} whoami

      # Build & Deploy
      - name: Deploy to remote server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_USERNAME }}
          TARGET: "/home/debian/Documents/jouskaio.me/WEB-Jouskaio.me"
          EXCLUDE: "/dist/, /node_modules/"
          SCRIPT_AFTER: |
            echo "Starting SCRIPT_AFTER"
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            cd /home/debian/Documents/jouskaio.me/WEB-Jouskaio.me
            git pull
            yarn install
            next build
            pm2 restart WEB-Jouskaio.me
            
