name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Mise à jour de l'action checkout
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      # Installe les dépendances
      - name: Install Dependencies
        run: npm install

      # Exécute les tests
      - name: Run Tests
        run: npm run test

      # Construit l'application Next.js
      - name: Build
        run: npm run build

      # Déploie l'application sur le serveur Linux
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/WEB-Jouskaio.me
            git pull origin main
            npm install
            npm run build
            pm2 restart nextjs
